name: Test

on:
  push:
    branches:
      - main
    paths:
      - "fastapi_inject/**"
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/**"
  workflow_dispatch: null

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Pull git repo
        uses: actions/checkout@v4

      - name: Install python version 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run tests with pytest
        run: |
          poetry run pytest --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov=fastapi_inject tests/ | tee pytest-coverage.txt
          test ${PIPESTATUS[0]} -eq 0

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - run: coverage html --title "FastAPI-Inject Coverage"

      - name: Store coverage html
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
